### ISSUE TITLE
Clone error

### ISSUE THREAD

**Issue by laiviet** [sinantie/NeuralAmr#1]
I got this error during clone this project.
'''
Smudge error: Error downloading models/20M_gen/amr-model_pretrain_epoch19_fine_tune_epoch21.00_4.69.t7 (fe8ccfb8629fbc39d1653481df7d8d743fd0ad78afe1c88a944d7c6e0264c314): batch response: This repository is over its data quota. Purchase more data packs to restore access.

'''
It seems the data bandwidth has exceeded the limit.
@sinantie : Can you move the big source files to another free cloud?
@others: If you have already completely cloned the large files, would you mind sending me the external link via email: vietld@jaist.ac.jp

Many thanks.

**Comment by sinantie** [comment]
Just added a public link to google drive [here](https://drive.google.com/file/d/0B0e2gHbz7CcIc0p1SjRhLVR2bTA/view?usp=sharing), containing the models folder in .zip format. It should be unzipped inside the project directory.

**Comment by nguyenlab** [comment]
Thank you so much!
