### ISSUE TITLE
Bug in AmrAlignment.isEmpty()

### ISSUE THREAD

**Issue by around1991** [sinantie/NeuralAmr#10]
Hi guys

I think the isEmpty method of the AmrAlignment class is incorrectly specified. When nodes are merged in the AMR traversal process (such as name and op nodes), their alignments also get merged, even if they haven't been created yet. This causes isEmpty to return true, and for the jamr alignment heuristic method to be not called.

This means, among other things, that running the code as is on the provided Little Prince dataset doesn't anonymize named entities. On the LDC AMR releases, this issue is masked, because alignments are specified directly on the nodes using the ~e.xx format.

The fix is pretty simple (I've implemented it locally) - should I open a pull request?

Thanks
Kris

**Comment by sinantie** [comment]
Good catch!
Sure, open a PR and will merge. 

Thanks!

Yannis
