### ISSUE TITLE
Warning of "Program should never enter here !"

### ISSUE THREAD

**Issue by freesunshine0316** [sinantie/NeuralAmr#5]
I process with the command of "./anonDeAnon_java.sh anonymizeAmrFull true train.amr.line > log", and find the following warning message.
I checked one input AMR, which looks Okay. I paste the AMR below:

Program should never enter here !

(m / mental :domain (t / transplant-01 :ARG1 (a / and-or :op1 (c / country :wiki "Israel" :name (n / name :op1 "Israel")) :op2 (c2 / country :wiki "State_of_Palestine" :name (n2 / name :op1 "Palestine"))) :ARG2 (c3 / country :wiki "United_Kingdom" :name (n3 / name :op1 "United Kingdom"))) :degree (a2 / absolute) :ARG1-of (s / say-01 :ARG0 (i / i))) 

Here is the full list:
Program should never enter here !

(p / possible-01 :mode interrogative :ARG1 (p2 / profile :ARG1-of (l / low-04) :ARG1-of (c / cause-01 :ARG0 (s / show-up-02 :ARG1 (n / name :poss (h / he)) :location (a / and :op1 (p3 / paper :mod (w / world-region :wiki "Middle_East" :name (n3 / name :op1 "Middle East"))) :op2 (p4 / paper :mod (c3 / continent :wiki "Europe" :name (n2 / name :op1 "Europe")))) :ARG0-of (r3 / regard-01 :ARG1 (b / bit :mod (c2 / company :wiki "Halliburton" :name (n4 / name :op1 "Halliburton")) :mod (s2 / same :degree (v / very)))) :time (n5 / now))))) 
Program should never enter here !

(m3 / multi-sentence :snt1 (r / resemble-01 :ARG1 (m4 / media :ARG0-of (c / condemn-01 :ARG1 (b / banker))) :ARG2 (h / hunt-01 :ARG1 (w / witch))) :snt2 (g / give-01 :ARG1 (b2 / bonus :mod (m5 / monetary-quantity :quant 6500000 :unit (p2 / pound)) :mod (j / just)) :ARG2 (p / person :wiki "Stephen_Hester" :name (n / name :op1 "Stephen" :op2 "Hester")) :time (d4 / date-entity :year 2010) :concession (p3 / pay-01 :ARG1 (m6 / monetary-quantity :quant 21000000 :unit (d5 / dollar)) :ARG2 (p4 / person :ARG0-of (h2 / have-org-role-91 :ARG1 (o / organization :wiki "JPMorgan_Chase" :name (n2 / name :op1 "JP Morgan")) :ARG3 (e / executive :mod (t / top)))) :time d4 :mod (y / yet)))) 
Program should never enter here !

(a / and :op1 (d / defeat-01 :ARG1 (p / power :mod (t / this) :mod (e / empire))) :op2 (p2 / pass-05 :ARG1 (p3 / power) :ARG2 (p4 / power :mod (a2 / another)) :time (t2 / then)) :ARG1-of (r / resemble-01 :ARG2 (b / become-01 :ARG1 (c / country :wiki "State_of_Palestine" :name (n / name :op1 "Palestine")) :ARG2 (m / mandate :poss (c2 / country :wiki "United_Kingdom" :name (n2 / name :op1 "United Kingdom")))))) 
Program should never enter here !

(t / think-01 :ARG0 (y / you) :ARG1 (a / and :op1 (i / invade-01 :ARG0 (c / country :ARG1-of (n / neighbor-01)) :ARG1 (s / state :mod (t3 / this) :mod (n2 / new))) :op2 (f / force-01 :ARG1 (p / person :source (c2 / country :wiki "United_Kingdom" :name (n3 / name :op1 "United Kingdom")) :mod (n4 / native)) :ARG2 (f2 / flee-05 :ARG0 p :ARG2 (a2 / and :op1 (p3 / province :wiki "Cornwall" :name (n6 / name :op1 "Cornwall") :ARG1-of (m / mean-01 :ARG2 (w / world-region :wiki "Gaza_Strip" :name (n13 / name :op1 "Gaza")))) :op2 (p4 / province :wiki "Yorkshire" :name (n7 / name :op1 "Yorkshire")) :op3 (p5 / province :wiki "Lincolnshire" :name (n8 / name :op1 "Lincolnshire")) :op4 (p6 / province :wiki "Norfolk" :name (n9 / name :op1 "Norfolk")) :op5 (p7 / province :wiki "Suffolk" :name (n10 / name :op1 "Suffolk")) :op6 (p8 / province :wiki "Essex" :name (n11 / name :op1 "Essex")) :op7 (p9 / part-of :op1 (c3 / city :wiki "East_London" :name (n12 / name :op1 "East" :op2 "London") :ARG1-of (m2 / mean-01 :ARG2 (c4 / country-region :wiki "West_Bank" :name (n14 / name :op1 "West" :op2 "Bank"))))))))) :time (t2 / then)) 
Program should never enter here !

(m / mental :domain (t / transplant-01 :ARG1 (a / and-or :op1 (c / country :wiki "Israel" :name (n / name :op1 "Israel")) :op2 (c2 / country :wiki "State_of_Palestine" :name (n2 / name :op1 "Palestine"))) :ARG2 (c3 / country :wiki "United_Kingdom" :name (n3 / name :op1 "United Kingdom"))) :degree (a2 / absolute) :ARG1-of (s / say-01 :ARG0 (i / i))) 
Program should never enter here !

(p / plan-01 :ARG0 (m / military :wiki "United_States_Navy" :name (n / name :op1 "USN")) :ARG1 (d / decommission-01 :ARG0 m :ARG1 (s2 / ship :wiki "USS_Osprey_(MHC-51)" :name (n2 / name :op1 "MHC 51 Osprey") :poss m :ARG0-of (h / hunt-01 :ARG1 (m2 / mine))) :manner (p2 / premature)) :mod (i / interesting))

**Comment by sinantie** [comment]
These AMR graphs have "syntactic errors" :) 
There shouldn't be spaces inside constants (or any other concept really). In the first example, (n3 / name :op1 "United Kingdom"), should become (n3 / name :op1 "United" :op2 "Kingdom")
